theme: jekyll-theme-minimal
title: Alex Carvalho
logo: "https://raw.githubusercontent.com/LexC/lexc.github.io/main/images/headshot.jpg" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Neuroscientist | Data Scientist | Scientific Programmer
  <br>
  To get in touch, please reach out via <a href="https://www.linkedin.com/in/alexccrv/">LinkedIn</a>
  <br>
  <br>
#show_downloads: true
